# Generated by Django 4.2.16 on 2025-01-04 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name_plural": "Positions"},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Nome Completo"),
                ),
                (
                    "emp_code",
                    models.CharField(
                        max_length=3, verbose_name="Código do Funcionário"
                    ),
                ),
                ("mobile", models.CharField(max_length=15)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_app.position",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employees",
            },
        ),
    ]
